### PR TITLE
Bug/40 styles get screwn up from time to time

### LINKED ISSUE #40: Styles get screwn up from time to time (maps)

### PR DESCRIPTION
**Pull request by nasdan**
Close #40

### CODE REVIEW

File: src/pages/_app.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
+import React from "react";
```
Comment (nasdan) [inline src/pages/_app.js:1]: - [Related issue](https://github.com/zeit/next-plugins/issues/282#issuecomment-432127816)

- [Custom App](https://github.com/zeit/next.js#custom-app)
